// DO NOT INCLUDE THIS HEADER
// THIS HEADER IS A PART OF ECKERT CONSTANTS

#ifdef _ECKERT_CONSTANTS_H_
#ifndef __ECKERT_CONSTANTS_ENUM_H_
#define __ECKERT_CONSTANTS_ENUM_H_

enum : unsigned int {
	// MASK
	UNSET = 0,
	UNMASKED_BITS = 8,
	U_MASK     = (~0U) << UNMASKED_BITS,
	// TYPE
	CONST_MATH  = 1 << UNMASKED_BITS,
	CONST_UNIV  = 2 << UNMASKED_BITS,
	CONST_ELEC  = 3 << UNMASKED_BITS,
	CONST_NUKE  = 4 << UNMASKED_BITS,
	CONST_CHEM  = 5 << UNMASKED_BITS,
	CONST_ADPT  = 6 << UNMASKED_BITS,
	CONST_PL    = 7 << UNMASKED_BITS,
	CONST_ASTRO = 8 << UNMASKED_BITS,
	// Math
	MATH_PI     = CONST_MATH | 1,
	MATH_NAPIER = CONST_MATH | 2,
	MATH_EGAMMA = CONST_MATH | 3,
	// Universal
	UNIV_C0   = CONST_UNIV | 1,
	UNIV_MU0  = CONST_UNIV | 2,
	UNIV_EPS0 = CONST_UNIV | 3,
	UNIV_Z0   = CONST_UNIV | 4,
	UNIV_G0   = CONST_UNIV | 5,
	UNIV_H    = CONST_UNIV | 6,
	UNIV_HBAR = CONST_UNIV | 7,
	// Electro-magnetic constant
	ELEC_E_CHARGE   = CONST_ELEC | 1,
	ELEC_Q_FLUX     = CONST_ELEC | 2,
	ELEC_Q_COND     = CONST_ELEC | 3,
	ELEC_Q_RESIST   = CONST_ELEC | 4,
	ELEC_JOSEPH     = CONST_ELEC | 5,
	ELEC_KLITZ      = CONST_ELEC | 6,
	ELEC_B_MAGNETON = CONST_ELEC | 7,
	ELEC_N_MAGNETON = CONST_ELEC | 8,
	// Nuclear physics
	NUKE_F_STRUCT = CONST_NUKE | 1,
	NUKE_RYDBERG  = CONST_NUKE | 2,
	NUKE_B_RADIUS = CONST_NUKE | 3,
	NUKE_HARTREE  = CONST_NUKE | 4,
	// electron
	NUKE_E_MASS     = CONST_NUKE | 5,
	NUKE_E_COMPTON  = CONST_NUKE | 6,
	NUKE_E_RADIUS   = CONST_NUKE | 7,
	NUKE_E_MAGNETIC = CONST_NUKE | 8,
	NUKE_E_GYRO     = CONST_NUKE | 9,
	// proton
	NUKE_P_MASS     = CONST_NUKE | 10,
	NUKE_P_COMPTON  = CONST_NUKE | 11,
	NUKE_P_MAGNETIC = CONST_NUKE | 12,
	NUKE_P_GYRO     = CONST_NUKE | 13,
	// neutron
	NUKE_N_MASS     = CONST_NUKE | 14,
	NUKE_N_COMPTON  = CONST_NUKE | 15,
	NUKE_N_MAGNETIC = CONST_NUKE | 16,
	NUKE_N_GYRO     = CONST_NUKE | 17,
	// elementary particle
	NUKE_MU_MASS     = CONST_NUKE | 18,
	NUKE_MU_MAGNETIC = CONST_NUKE | 19,
	NUKE_TAU_MASS    = CONST_NUKE | 20,
	// physical chemistry
	CHEM_BOLTZMANN = CONST_CHEM | 1,
	CHEM_AVOGADRO  = CONST_CHEM | 2,
	CHEM_DALTON    = CONST_CHEM | 3,
	CHEM_FARADAY   = CONST_CHEM | 4,
	CHEM_GAS       = CONST_CHEM | 5,
	CHEM_MOLVOL    = CONST_CHEM | 6,
	CHEM_MOLVOL_L  = CONST_CHEM | 7,
	CHEM_LOSCHMIDT = CONST_CHEM | 8,
	// thermal radiation
	CHEM_STEFAN = CONST_CHEM | 9,
	CHEM_F_RAD  = CONST_CHEM | 10,
	CHEM_S_RAD  = CONST_CHEM | 11,
	// adopted value
	ADPT_G0    = CONST_ADPT | 1,
	ADPT_ATM   = CONST_ADPT | 2,
	ADPT_ZDEG  = CONST_ADPT | 3,
	// Planck unit
	PL_MASS   = CONST_PL | 1,
	PL_ENERGY = CONST_PL | 2,
	PL_TEMP   = CONST_PL | 3,
	PL_LENGTH = CONST_PL | 4,
	PL_TIME   = CONST_PL | 5,
	// astromy
	ASTRO_AU = CONST_ASTRO | 1,
	ASTRO_PC = CONST_ASTRO | 2,
	ASTRO_LY = CONST_ASTRO | 3,
};

#endif // ifndef __ECKERT_CONSTANTS_ENUM_H_
#endif // ifdef _ECKERT_CONSTANTS_H_
